### PR TITLE
Update server_extend recipe with fqdn for peering

### PR DESCRIPTION
**Pull request by shortdudey123**
Addresses the comments in https://github.com/shortdudey123/chef-gluster/commit/e1c84e2ad6058ddcddc959458a3f119288809e90 as well as partially fixes https://github.com/shortdudey123/chef-gluster/issues/29

@Seth-Karlo thoughts?

### CODE REVIEW

**Comment by shortdudey123** [comment]
@Seth-Karlo going to merge this Monday unless you have thoughts

**Comment by Seth-Karlo** [comment]
As I said in the original comment I think this is a bad idea. By removing people's ability to change the peer list to suit their environment it creates additional challenges. I needed to create a highly available reliable cluster solution and have now forked, you are welcome to take any code you wish from it as it remains open source, but this particular change was the last in a list of issues which prevented this cookbook from being able to create a reliable gluster setup, which is something we needed. The code I am now contributing to is here: https://github.com/schubergphilis/sbp_gluster

I'm sorry for forking, but the original code was so broken and you and I have different views on how this cookbook should be. I hope we can converge in the future.

**Comment by shortdudey123** [comment]
@Seth-Karlo What would be a better solution then?

Your solution assumes the chef node name is an FQDN or something that resolvs via DNS.  (Unless you use hosts files)

My solution assumes that the nodes have an FQDN that can be used to access each other.

**Comment by Seth-Karlo** [comment]
@shortdudey123 The peer list should be whatever people want it to be. By forcing the change to FQDN you remove the flexibility for people to use hostnames, fqdn's or even IP addresses in their environment depending on what works for them. You've removed that flexibility.

**Comment by shortdudey123** [comment]
Hmm, ok

Thoughts about this solution:
Peer list = chef node name (can't really get around this one vary easily)
Gluster peering = ip, node name, or FQDN (option set via an attribute)

**Comment by Seth-Karlo** [comment]
@shortdudey123 You actually do not need to do a node load at all. See my changes here:
https://github.com/schubergphilis/sbp_gluster/blob/master/recipes/server_setup.rb#L85

Because all of the nodes are running the exact same code, the brick path will be identical on all of them, so you can skip the node load and just set the attributes based on what the 'master' node is doing. The peer list doesn't need to be loaded by chef at all or manipulated by it, just let chef pass it to gluster.

**Comment by shortdudey123** [comment]
Ah, you are very correct!  I completely missed that.

Can you put a PR in w/ those changes? (LVM too) and i will close this one.

**Comment by Seth-Karlo** [comment]
@shortdudey123 Sure thing, but it'll take me some time to pull it out of my fork. Will try and sort it tomorrow.

**Comment by shortdudey123** [comment]
Sure, np

**Pull request closed without merging**
