### PR TITLE
Added support for Upstart.

### PR DESCRIPTION
**Pull request by leoditommaso**
When using this cookbook on Ubuntu 14.04 it was failing to either enable
or start the service.

### CODE REVIEW

**Comment by shortdudey123** [comment]
will review once tests pass

**Comment by leoditommaso** [comment]
Fixed!

**Comment by leoditommaso** [comment]
@shortdudey123 as tests have passed, could this be merged? Thanks!

**Comment by shortdudey123** [comment]
It looks like chef will default to upstart if an upstart script for the service is present (see https://github.com/chef/chef/blob/a52dee886b6635fbc0fcca6cbb04d28bbdaed9e6/lib/chef/provider/service.rb#L204)

**Comment by leoditommaso** [comment]
Ok, it looks it will, but it's not in v11.18.0 (https://github.com/chef/chef/blob/11.18.0/lib/chef/provider/service.rb) which is the one I'm currently using.

**Comment by shortdudey123** [comment]
Yeah, looks like it was added in chef 12.
Can you add a chef version chef for < 12?

**Comment by leoditommaso** [comment]
Ok, I'll do it tomorrow.

On Tue, Sep 29, 2015 at 18:42, shortdudey123/chef-gluster
<reply@reply.github.com>
wrote:
Yeah, looks like it was added in chef 12.
Can you add a chef version chef for < 12?

—
Reply to this email directly or view it on GitHub
[https://github.com/shortdudey123/chef-gluster/pull/30#issuecomment-144199848] .[https://github.com/notifications/beacon/AEH0tF3flVSgK5T9_4vdPUlJX1d8HH0mks5o2v1PgaJpZM4GBN3t.gif]

**Comment by shortdudey123** [comment]
Cool, will merge this once the chef version check is added

**Comment by shortdudey123** [comment]
@leoditommaso any update on the Chef version chef? also, can you rebase your commits into 1 once you are done?

**Comment by shortdudey123** [comment]
Closing due to inactivity

**Pull request closed without merging**
