### PR TITLE
making client works with CentOS

### PR DESCRIPTION
**Pull request by tmoreau**

### CODE REVIEW

**Comment by shortdudey123** [comment]
@tmoreau did you want this reviewed and merged? or no?

**Comment by tmoreau** [comment]
you can discard, has been replaced by PR #33
sorry for the noise...

**Comment by shortdudey123** [comment]
np, https://github.com/shortdudey123/chef-gluster/commit/972713ccb83873b569e71045e34ebbc02207a464 would be nice to have too :)

**Comment by shortdudey123** [comment]
ah see that in 34, nvm

**Pull request closed without merging**
